version: 2

sources:
  - name: u_marlonmenjivar
    schema: u_marlonmenjivar
    tables:
      - name: jaffle_shop_customers
        description: Raw customers data
        columns:
          - name: id
            description: Primary key for customers
            tests:
              - unique
              - not_null
      - name: jaffle_shop_orders
        description: Raw orders data
        columns:
          - name: id
            description: Primary key for orders
            tests:
              - unique
              - not_null
      - name: stripe_payments
        loaded_at_field: created
        freshness:
          warn_after: { count: 12, period: hour }
          error_after: { count: 24, period: hour }
